name: surethingnet
description: "SureThingNet: My Home Network Security App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.5

  # Platform & Hardware Integration
  mobile_scanner: ^5.0.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  # Icons & UI helpers
  cupertino_icons: ^1.0.6
  network_info_plus: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
